### PR TITLE
Setting initial button as nullable on init view.

### PR DESCRIPTION
**Pull request by AhmedGaberAbass**
Hello, how are you, I hope you are fine
 - Thank you for this wonderful library.
 - But after using the library I got a problem (IlligalArgumentException) in jcNotificationPlayer.createNotificationPlayer.
 - This problem only appears in Android 10 by 40% and Android 11 by 60%.
 - It appears to me that the problem exists in
 NotificationManager.java
 Line 622, 601, 535
 and in
 NotificationManagerCompat.java
 Line 223, 205
 And at jcNotificationPlayer.kt
 Line 95, 154
 and in
 JcPlayerManager.kt
 Line 273
 and in
 JcPlayerServices.kt
 Line [د232

### CODE REVIEW

**Comment by AhmedGaberAbass** [comment]
Screenshot_٢٠٢٢-٠٣-٢٧-٠١-٣٦-٤٧-٦٦٩_com google android apps playconsole

**Comment by AhmedGaberAbass** [comment]
But the file read only
How can i edite this lines

**Comment by jeancsanchez** [comment]
Hello @AhmedGaberAbass thank you for the report. 

If you already have a solution, please clone this project and open a new pull request with it.

**Comment by AhmedGaberAbass** [comment]
Thank you for your cooperation
But I don't understand anything yet?

‫في الأحد، 27 مارس 2022 في 2:39 ص تمت كتابة ما يلي بواسطة ‪Jean Carlos‬‏ <‪
***@***.***‬‏>:‬

**Comment by AhmedGaberAbass** [comment]
Hello jean
how are you I hope you are fine
The notification was on the default mode causing problems but after I set
the notification icon now the app works without problems 🥰🥰🥰🥰
Thanks 👍👍👍👍👍👍👍

في الأحد، ٢٧ مارس ٢٠٢٢ ٩:٥٥ ص الفنان للمعلوميات ***@***.***>
كتب:

**Pull request closed without merging**
